name: Deploy Infrastructure

on:
  push:
    branches: [ "main" ]
    paths: [ "live/**", "modules/**" ] # Solo corre si cambias config

    
jobs:
  terragrunt:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Necesario para Workload Identity

    env:
      # Opci贸n A: Si lo guardaste en Secrets (Recomendado para IDs sensibles)
      GOOGLE_PROJECT_ID: ${{ vars.GCP_PROJECT }}

    steps:
     # Checkout del c贸digo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Autenticaci贸n con Google Cloud
      - name: Set up Google Cloud Auth (Service Account Key)
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} 

      # Configurar gcloud y Terraform
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
                TG_VERSION="v0.54.12" # O la versi贸n que prefieras
                echo "Installing Terragrunt $TG_VERSION..."
                wget -q "https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64"
                chmod +x terragrunt_linux_amd64
                sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
                terragrunt --version

      - name: Terragrunt Plan
        # run-all ejecuta en paralelo respetando dependencias
        run: cd live/dev && terragrunt run-all plan --terragrunt-non-interactive

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main'
        run: cd live/dev && terragrunt run-all apply --terragrunt-non-interactive