name: Deploy Infrastructure

on:
  push:
    branches: [ "main" ]
    paths: [ "live/**", "modules/**" ] # Solo corre si cambias config

    
jobs:
  terragrunt:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Necesario para Workload Identity

    steps:
      - uses: actions/checkout@v3

      - name: üïµÔ∏è Debug - List files
        run: |
          echo "Listing live/dev structure:"
          ls -R *

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'terraform-sa@mi-proyecto.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
                TG_VERSION="v0.54.12" # O la versi√≥n que prefieras
                echo "Installing Terragrunt $TG_VERSION..."
                wget -q "https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64"
                chmod +x terragrunt_linux_amd64
                sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
                terragrunt --version

      - name: Terragrunt Plan
        # run-all ejecuta en paralelo respetando dependencias
        run: cd live/dev && terragrunt run-all plan --terragrunt-non-interactive

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main'
        run: cd live/dev && terragrunt run-all apply --terragrunt-non-interactive