name: Deploy Infrastructure

on:
  push:
    branches: [ "main" ]
    paths: [ "live/**", "modules/**", ".github/**" ] 
#on:
#  workflow_dispatch:
#    inputs:
#      confirm:
#        description: 'Escribe "deploy" para confirmar la eliminaci√≥n de GKE'
#        required: true
#        default: 'deploy'

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      GOOGLE_PROJECT_ID: ${{ vars.GCP_PROJECT }}
      GOOGLE_REGION: ${{ vars.GCP_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud Auth (Service Account Key)
        uses: 'google-github-actions/auth@v2'
        with:
#         credentials_json: ${{ secrets.GCP_SA_KEY }} 
          workload_identity_provider: 'projects/397005106927/locations/global/workloadIdentityPools/github-actions-pool/providers/provider-fix'
          service_account: 'github-actions-sa@lakehouse-475923.iam.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
                TG_VERSION="v0.54.12"
                echo "Installing Terragrunt $TG_VERSION..."
                wget -q "https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64"
                chmod +x terragrunt_linux_amd64
                sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
                terragrunt --version

      - name: Terragrunt Plan
        run: cd live/dev && terragrunt run-all plan --terragrunt-non-interactive

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main'
        run: cd live/dev && terragrunt run-all apply --terragrunt-non-interactive