name: Destroy GKE Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Escribe "destroy" para confirmar la eliminación de GKE'
        required: true
        default: 'destroy'

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT }}
  TF_VAR_region: us-central1-a

jobs:
  destroy:
    name: "Terragrunt Destroy"
    runs-on: ubuntu-latest

    # Solo ejecuta si el usuario confirma escribiendo 'destroy'
    if: github.event.inputs.confirm == 'destroy'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Autenticación con Google Cloud
      - name: Set up Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
#         credentials_json: ${{ secrets.GCP_SA_KEY }} 
          workload_identity_provider: 'projects/397005106927/locations/global/workloadIdentityPools/github-actions-pool/providers/provider-fix'
          service_account: 'github-actions-sa@lakehouse-475923.iam.gserviceaccount.com'


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          TG_VERSION="v0.54.12"
          echo "Installing Terragrunt $TG_VERSION..."
          wget -q "https://github.com/gruntwork-io/terragrunt/releases/download/${TG_VERSION}/terragrunt_linux_amd64"
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version

      - name: Terragrunt Destroy
        working-directory: live/dev
        run: |
          terragrunt run-all destroy --terragrunt-non-interactive